// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.AI.Actions.Hosting.h"
#include "Windows.ApplicationModel.Contacts.h"
#include "Windows.UI.h"

/* Forward Declarations */
#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntity __x_ABI_CWindows_CAI_CActions_CIActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntity2_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntity2_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntity2 __x_ABI_CWindows_CAI_CActions_CIActionEntity2;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntity2_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2 __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3 __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4 __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionFeedback_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionFeedback_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionFeedback __x_ABI_CWindows_CAI_CActions_CIActionFeedback;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionFeedback_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2 __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionRuntime_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime __x_ABI_CWindows_CAI_CActions_CIActionRuntime;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionRuntime_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime2 __x_ABI_CWindows_CAI_CActions_CIActionRuntime2;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime3 __x_ABI_CWindows_CAI_CActions_CIActionRuntime3;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory;

#endif // ____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIContactActionEntity __x_ABI_CWindows_CAI_CActions_CIContactActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIFileActionEntity __x_ABI_CWindows_CAI_CActions_CIFileActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CINamedActionEntity __x_ABI_CWindows_CAI_CActions_CINamedActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs;

#endif // ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter;

#endif // ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CITableActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CITableActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CITableActionEntity __x_ABI_CWindows_CAI_CActions_CITableActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CITableActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CITextActionEntity_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CITextActionEntity_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CITextActionEntity __x_ABI_CWindows_CAI_CActions_CITextActionEntity;

#endif // ____x_ABI_CWindows_CAI_CActions_CITextActionEntity_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CITextActionEntity2 __x_ABI_CWindows_CAI_CActions_CITextActionEntity2;

#endif // ____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#if !defined(____x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__

    typedef interface __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs;

    //  Declare the parameterized interface IID.
    EXTERN_C const IID IID___x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs;

    typedef struct __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs* This);
        HRESULT (STDMETHODCALLTYPE* Invoke)(__x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs* This,
        __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* sender,
        __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* args);

        END_INTERFACE
    } __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgsVtbl;

    interface __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs
    {
        CONST_VTBL struct __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgsVtbl* lpVtbl;
    };

    
    #endif // ____x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__
    
#ifndef ____x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog __x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog;

#endif // ____x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CApplicationModel_CContacts_CIContact_FWD_DEFINED__
#define ____x_ABI_CWindows_CApplicationModel_CContacts_CIContact_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CApplicationModel_CContacts_CIContact __x_ABI_CWindows_CApplicationModel_CContacts_CIContact;

#endif // ____x_ABI_CWindows_CApplicationModel_CContacts_CIContact_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIUriRuntimeClass __x_ABI_CWindows_CFoundation_CIUriRuntimeClass;

#endif // ____x_ABI_CWindows_CFoundation_CIUriRuntimeClass_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CUI_CWindowId __x_ABI_CWindows_CUI_CWindowId;

typedef enum __x_ABI_CWindows_CAI_CActions_CActionEntityKind __x_ABI_CWindows_CAI_CActions_CActionEntityKind;

typedef enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat;

typedef enum __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind;

typedef enum __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind;

typedef enum __x_ABI_CWindows_CAI_CActions_CActionInvocationResult __x_ABI_CWindows_CAI_CActions_CActionInvocationResult;

typedef enum __x_ABI_CWindows_CAI_CActions_CRemoteFileKind __x_ABI_CWindows_CAI_CActions_CRemoteFileKind;

enum __x_ABI_CWindows_CAI_CActions_CActionEntityKind
    {
        __x_ABI_CWindows_CAI_CActions_CActionEntityKind_None = 0,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_Document = 1,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_File = 2,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_Photo = 3,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_Text = 4,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_StreamingText = 5,
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_RemoteFile = 6,
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_Table = 7,
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
    __x_ABI_CWindows_CAI_CActions_CActionEntityKind_Contact = 8,
#endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
};

enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat
    {
        __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat_Plain = 0,
    __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat_Markdown = 1,
};

enum __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind
    {
        __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind_Positive = 0,
    __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind_Negative = 1,
};

enum __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind
    {
        __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind_None = 0,
    __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind_Error = 1,
    __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind_Warning = 2,
};

enum __x_ABI_CWindows_CAI_CActions_CActionInvocationResult
    {
        __x_ABI_CWindows_CAI_CActions_CActionInvocationResult_Success = 0,
    __x_ABI_CWindows_CAI_CActions_CActionInvocationResult_UserCanceled = 1,
    __x_ABI_CWindows_CAI_CActions_CActionInvocationResult_Unsupported = 2,
    __x_ABI_CWindows_CAI_CActions_CActionInvocationResult_Unavailable = 3,
};

enum __x_ABI_CWindows_CAI_CActions_CRemoteFileKind
    {
        __x_ABI_CWindows_CAI_CActions_CRemoteFileKind_Document = 0,
    __x_ABI_CWindows_CAI_CActions_CRemoteFileKind_Photo = 1,
    __x_ABI_CWindows_CAI_CActions_CRemoteFileKind_File = 2,
};

#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Kind)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityKind* value);
    HRESULT (STDMETHODCALLTYPE* get_DisplayInfo)(__x_ABI_CWindows_CAI_CActions_CIActionEntity* This,
        __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo** value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntity2_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntity2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntity2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Id)(__x_ABI_CWindows_CAI_CActions_CIActionEntity2* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntity2Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntity2
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntity2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntity2;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntity2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfoVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Title)(__x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfoVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfoVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityDisplayInfo_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateFileEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
        HSTRING path,
        __x_ABI_CWindows_CAI_CActions_CIFileActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreateDocumentEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
        HSTRING path,
        __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreatePhotoEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
        HSTRING path,
        __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreateTextEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2* This,
        HSTRING text,
        __x_ABI_CWindows_CAI_CActions_CITextActionEntity** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateRemoteFileEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
        HSTRING sourceId,
        enum __x_ABI_CWindows_CAI_CActions_CRemoteFileKind fileKind,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* sourceUri,
        HSTRING fileId,
        HSTRING contentType,
        HSTRING driveId,
        HSTRING accountId,
        HSTRING extension,
        __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreateTextEntityWithTextFormat)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
        HSTRING text,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat textFormat,
        __x_ABI_CWindows_CAI_CActions_CITextActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreateStreamingTextActionEntityWriter)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat textFormat,
        __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory3_INTERFACE_DEFINED__) */
    
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateTableEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
        UINT32 dataLength,
        HSTRING* data,
        UINT32 columnCount,
        __x_ABI_CWindows_CAI_CActions_CITableActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* CreateContactEntity)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4* This,
        __x_ABI_CWindows_CApplicationModel_CContacts_CIContact* contact,
        __x_ABI_CWindows_CAI_CActions_CIContactActionEntity** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactory4_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionEntityFactoryFactory_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionFeedback_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionFeedback_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionFeedbackVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FeedbackKind)(__x_ABI_CWindows_CAI_CActions_CIActionFeedback* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionFeedbackVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionFeedback
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionFeedbackVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionFeedback;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionFeedback_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationContextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_EntityFactory)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2** value);
    HRESULT (STDMETHODCALLTYPE* SetInputEntity)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        HSTRING inputName,
        __x_ABI_CWindows_CAI_CActions_CIActionEntity* inputValue);
    HRESULT (STDMETHODCALLTYPE* GetInputEntities)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        UINT32* resultLength,
        __x_ABI_CWindows_CAI_CActions_CINamedActionEntity*** result);
    HRESULT (STDMETHODCALLTYPE* SetOutputEntity)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        HSTRING outputName,
        __x_ABI_CWindows_CAI_CActions_CIActionEntity* outputValue);
    HRESULT (STDMETHODCALLTYPE* GetOutputEntities)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        UINT32* resultLength,
        __x_ABI_CWindows_CAI_CActions_CINamedActionEntity*** result);
    HRESULT (STDMETHODCALLTYPE* get_Result)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionInvocationResult* value);
    HRESULT (STDMETHODCALLTYPE* put_Result)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionInvocationResult value);
    HRESULT (STDMETHODCALLTYPE* get_ExtendedError)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        HRESULT* value);
    HRESULT (STDMETHODCALLTYPE* put_ExtendedError)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext* This,
        HRESULT value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionInvocationContextVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationContextVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionInvocationContext;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_InvokerWindowId)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
        struct __x_ABI_CWindows_CUI_CWindowId* value);
    HRESULT (STDMETHODCALLTYPE* get_HelpDetails)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
        __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails** value);
    HRESULT (STDMETHODCALLTYPE* get_ActionId)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_InvokerAppUserModelId)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationContext2_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetailsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Kind)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind* value);
    HRESULT (STDMETHODCALLTYPE* put_Kind)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionInvocationHelpKind value);
    HRESULT (STDMETHODCALLTYPE* get_Title)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Title)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Description)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Description)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_HelpUri)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* put_HelpUri)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass* value);
    HRESULT (STDMETHODCALLTYPE* get_HelpUriDescription)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_HelpUriDescription)(__x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails* This,
        HSTRING value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetailsVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetailsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionInvocationHelpDetails_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionRuntimeVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ActionCatalog)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
        __x_ABI_CWindows_CAI_CActions_CHosting_CIActionCatalog** value);
    HRESULT (STDMETHODCALLTYPE* get_EntityFactory)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
        __x_ABI_CWindows_CAI_CActions_CIActionEntityFactory2** value);
    HRESULT (STDMETHODCALLTYPE* CreateInvocationContext)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime* This,
        HSTRING actionId,
        __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionRuntimeVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionRuntimeVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionRuntime;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionRuntime2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateActionFeedback)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionFeedbackKind feedbackKind,
        __x_ABI_CWindows_CAI_CActions_CIActionFeedback** result);
    HRESULT (STDMETHODCALLTYPE* SetActionAvailability)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
        HSTRING actionId,
        boolean isAvailable);
    HRESULT (STDMETHODCALLTYPE* GetActionAvailability)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime2* This,
        HSTRING actionId,
        boolean* result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionRuntime2Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime2
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionRuntime2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionRuntime2;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime2_INTERFACE_DEFINED__) */
    
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionRuntime3Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* CreateInvocationContextWithWindowId)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
        HSTRING actionId,
        struct __x_ABI_CWindows_CUI_CWindowId invokerWindowId,
        __x_ABI_CWindows_CAI_CActions_CIActionInvocationContext** result);
    HRESULT (STDMETHODCALLTYPE* GetActionEntityById)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
        HSTRING entityId,
        __x_ABI_CWindows_CAI_CActions_CIActionEntity** result);
    HRESULT (STDMETHODCALLTYPE* get_LatestSupportedSchemaVersion)(__x_ABI_CWindows_CAI_CActions_CIActionRuntime3* This,
        UINT32* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionRuntime3Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionRuntime3
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionRuntime3Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionRuntime3;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntime3_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIActionRuntimeFactory_INTERFACE_DEFINED__) */
    
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIContactActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Contact)(__x_ABI_CWindows_CAI_CActions_CIContactActionEntity* This,
        __x_ABI_CWindows_CApplicationModel_CContacts_CIContact** value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIContactActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIContactActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIContactActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIContactActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIContactActionEntity_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if !defined(____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FullPath)(__x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIDocumentActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIDocumentActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIFileActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FullPath)(__x_ABI_CWindows_CAI_CActions_CIFileActionEntity* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIFileActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIFileActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIFileActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIFileActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIFileActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CINamedActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Name)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* put_Name)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
        HSTRING value);
    HRESULT (STDMETHODCALLTYPE* get_Entity)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
        __x_ABI_CWindows_CAI_CActions_CIActionEntity** value);
    HRESULT (STDMETHODCALLTYPE* put_Entity)(__x_ABI_CWindows_CAI_CActions_CINamedActionEntity* This,
        __x_ABI_CWindows_CAI_CActions_CIActionEntity* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CINamedActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CINamedActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CINamedActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CINamedActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CINamedActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_FullPath)(__x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIPhotoActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIPhotoActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_SourceId)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_FileKind)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        enum __x_ABI_CWindows_CAI_CActions_CRemoteFileKind* value);
    HRESULT (STDMETHODCALLTYPE* get_SourceUri)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass** value);
    HRESULT (STDMETHODCALLTYPE* get_FileId)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_ContentType)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_DriveId)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_AccountId)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Extension)(__x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIRemoteFileActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_IsComplete)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
        boolean* value);
    HRESULT (STDMETHODCALLTYPE* GetText)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
        HSTRING* result);
    HRESULT (STDMETHODCALLTYPE* get_TextFormat)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat* value);
    HRESULT (STDMETHODCALLTYPE* add_TextChanged)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
        __x_ABI_C__FITypedEventHandler_2___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntity___x_ABI_CWindows__CAI__CActions__CStreamingTextActionEntityTextChangedArgs* handler,
        EventRegistrationToken* token);
    HRESULT (STDMETHODCALLTYPE* remove_TextChanged)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity* This,
        EventRegistrationToken token);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgsVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Text)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_IsComplete)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs* This,
        boolean* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgsVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgsVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityTextChangedArgs_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriterVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_ReaderEntity)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
        __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntity** value);
    HRESULT (STDMETHODCALLTYPE* get_TextFormat)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat* value);
    HRESULT (STDMETHODCALLTYPE* SetText)(__x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter* This,
        HSTRING text);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriterVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriterVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CIStreamingTextActionEntityWriter_INTERFACE_DEFINED__) */
    
#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CActions_CITableActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CITableActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CITableActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetTextContent)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
        UINT32* resultLength,
        HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* get_RowCount)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
        UINT32* value);
    HRESULT (STDMETHODCALLTYPE* get_ColumnCount)(__x_ABI_CWindows_CAI_CActions_CITableActionEntity* This,
        UINT32* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CITableActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CITableActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CITableActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CITableActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CITableActionEntity_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if !defined(____x_ABI_CWindows_CAI_CActions_CITextActionEntity_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CITextActionEntity_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CITextActionEntityVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Text)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity* This,
        HSTRING* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CITextActionEntityVtbl;

    interface __x_ABI_CWindows_CAI_CActions_CITextActionEntity
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CITextActionEntityVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CITextActionEntity;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CITextActionEntity_INTERFACE_DEFINED__) */
    
#if !defined(____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CActions_CITextActionEntity2Vtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_TextFormat)(__x_ABI_CWindows_CAI_CActions_CITextActionEntity2* This,
        enum __x_ABI_CWindows_CAI_CActions_CActionEntityTextFormat* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CActions_CITextActionEntity2Vtbl;

    interface __x_ABI_CWindows_CAI_CActions_CITextActionEntity2
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CActions_CITextActionEntity2Vtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CActions_CITextActionEntity2;
#endif /* !defined(____x_ABI_CWindows_CAI_CActions_CITextActionEntity2_INTERFACE_DEFINED__) */
    
