// WARNING: Please don't edit this file. It was generated by Swift/WinRT v0.0.1

#pragma once
// Header files for imported files
#include <inspectable.h>
#include <EventToken.h>
#include <windowscontracts.h>
#include "Windows.Foundation.h"
#include "Windows.ApplicationModel.h"
#include "Windows.UI.h"

/* Forward Declarations */
#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory;

#endif // ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_FWD_DEFINED__

// Parameterized interface forward declarations (C)

// Collection interface definitions

#ifndef ____x_ABI_CWindows_CApplicationModel_CIPackage_FWD_DEFINED__
#define ____x_ABI_CWindows_CApplicationModel_CIPackage_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CApplicationModel_CIPackage __x_ABI_CWindows_CApplicationModel_CIPackage;

#endif // ____x_ABI_CWindows_CApplicationModel_CIPackage_FWD_DEFINED__

#ifndef ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
#define ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__
    typedef interface __x_ABI_CWindows_CFoundation_CIClosable __x_ABI_CWindows_CFoundation_CIClosable;

#endif // ____x_ABI_CWindows_CFoundation_CIClosable_FWD_DEFINED__

typedef struct __x_ABI_CWindows_CUI_CWindowId __x_ABI_CWindows_CUI_CWindowId;

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* put_OwnerWindowId)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
        struct __x_ABI_CWindows_CUI_CWindowId value);
    HRESULT (STDMETHODCALLTYPE* get_OwnerWindowId)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* This,
        struct __x_ABI_CWindows_CUI_CWindowId* value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContextFactory_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Command)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* GetCommandArguments)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
        UINT32* resultLength,
        HSTRING** result);
    HRESULT (STDMETHODCALLTYPE* get_Info)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer* This,
        __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo** value);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* GetServerInfos)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
        UINT32* resultLength,
        __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo*** result);
    HRESULT (STDMETHODCALLTYPE* ActivateServer)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
        GUID serverId,
        __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext* client,
        __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServer** result);
    HRESULT (STDMETHODCALLTYPE* CreateClientContext)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog* This,
        __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolClientContext** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalog_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerCatalogFactory_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
            TrustLevel* trustLevel);
        HRESULT (STDMETHODCALLTYPE* get_Id)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
        GUID* value);
    HRESULT (STDMETHODCALLTYPE* get_Name)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* get_Description)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
        HSTRING* value);
    HRESULT (STDMETHODCALLTYPE* GetPackage)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo* This,
        __x_ABI_CWindows_CApplicationModel_CIPackage** result);

        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfo_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

#if defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)
#if !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_INTERFACE_DEFINED__)
    #define ____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_INTERFACE_DEFINED__
    typedef struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactoryVtbl
    {
        BEGIN_INTERFACE

        HRESULT (STDMETHODCALLTYPE* QueryInterface)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This,
            REFIID riid,
            void** ppvObject);
        ULONG (STDMETHODCALLTYPE* AddRef)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This);
        ULONG (STDMETHODCALLTYPE* Release)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This);
        HRESULT (STDMETHODCALLTYPE* GetIids)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This,
            ULONG* iidCount,
            IID** iids);
        HRESULT (STDMETHODCALLTYPE* GetRuntimeClassName)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This,
            HSTRING* className);
        HRESULT (STDMETHODCALLTYPE* GetTrustLevel)(__x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory* This,
            TrustLevel* trustLevel);
    
        END_INTERFACE
    } __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactoryVtbl;

    interface __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory
    {
        CONST_VTBL struct __x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactoryVtbl* lpVtbl;
    };

    
    EXTERN_C const IID IID___x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory;
#endif /* !defined(____x_ABI_CWindows_CAI_CModelContextProtocol_CIModelContextProtocolServerInfoFactory_INTERFACE_DEFINED__) */
    #endif // defined(ENABLE_WINRT_EXPERIMENTAL_TYPES)

